version: "2"
services:
#    www:
#        build: .
#        ports: 
#            - "8001:80"
#        volumes:
#            - ./MVC:/var/www/html/
#        links:
#            - db
#        networks:
#            - default
    db:
        image: mysql:5.7
        ports: 
            - "3306:3306"
        environment:
            MYSQL_DATABASE: myDb
            MYSQL_USER: user
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test
        volumes:
            #- ./dump:/docker-entrypoint-initdb.d
            - ./volumen/mysql:/var/lib/mysql
        networks:
            - default
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links: 
            - db:db
        ports:
            - 8001:80
        environment:
            MYSQL_USER: user
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test
volumes:
    persistent: